# Generated by Django 3.1.3 on 2020-12-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201228_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='ordered',
            field=models.BooleanField(default=True),
        ),
    ]
