# Generated by Django 3.1.3 on 2021-01-04 13:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_address',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
